const mockCategories = [
  { _id: 'cat111111111111111111111', name: 'Electronics', slug: 'electronics', icon: '💻', description: 'Gadgets, devices, and accessories' },
  { _id: 'cat222222222222222222222', name: 'Fashion', slug: 'fashion', icon: '👗', description: 'Clothing, footwear, and apparel' },
  { _id: 'cat333333333333333333333', name: 'Home & Living', slug: 'home-living', icon: '🏠', description: 'Furniture, decor, and home essentials' },
  { _id: 'cat444444444444444444444', name: 'Beauty', slug: 'beauty', icon: '💄', description: 'Cosmetics, makeup, and skincare' },
  { _id: 'cat555555555555555555555', name: 'Sports', slug: 'sports', icon: '🏋️', description: 'Fitness gear, sportswear, and equipment' },
  { _id: 'cat666666666666666666666', name: 'Books', slug: 'books', icon: '📚', description: 'Books, novels, and stationery' },
  { _id: 'cat777777777777777777777', name: 'Toys & Games', slug: 'toys', icon: '🎮', description: 'Toys, board games, and puzzles' },
  { _id: 'cat888888888888888888888', name: 'Food & Grocery', slug: 'food', icon: '🛒', description: 'Gourmet foods, coffee, and daily groceries' },
];

const mockProducts = [
  {
    _id: '6a1fdb4e52daecb390f3d111',
    title: 'Sony WH-1000XM4 Wireless Headphones',
    description: 'Industry-leading noise-canceling wireless overhead headphones with smart listening technology, built-in mic for phone calls, and Alexa voice control.',
    brand: 'Sony',
    category: mockCategories[0],
    price: 348.0,
    discountPrice: 298.0,
    images: [{ public_id: 'sony_headphones_1', url: '/images/headphones.jpg' }],
    stock: 25,
    SKU: 'SONY-WH1000XM4-B',
    ratings: 4.8,
    numReviews: 120,
    specifications: { color: 'Black', connectivity: 'Bluetooth 5.0, NFC', battery_life: 'Up to 30 hours' },
    tags: ['headphones', 'wireless', 'sony', 'audio', 'electronics'],
    isFeatured: true,
    isActive: true
  },
  {
    _id: '6a1fdb4e52daecb390f3d112',
    title: 'Apple iPhone 15 Pro (128GB)',
    description: 'Titanium design, A17 Pro chip, customizable Action button, and the most powerful iPhone camera system ever.',
    brand: 'Apple',
    category: mockCategories[0],
    price: 999.0,
    discountPrice: 949.0,
    images: [{ public_id: 'iphone_15_pro', url: '/images/iphone.jpg' }],
    stock: 15,
    SKU: 'APL-IP15P-128-G',
    ratings: 4.9,
    numReviews: 48,
    specifications: { color: 'Natural Titanium', storage: '128GB', screen_size: '6.1 inches' },
    tags: ['iphone', 'apple', 'smartphone', 'mobile', 'electronics'],
    isFeatured: true,
    isActive: true
  },
  {
    _id: '6a1fdb4e52daecb390f3d113',
    title: 'Floral Summer Maxi Dress',
    description: 'Lightweight, breathable floral print maxi dress featuring an elegant v-neck, adjustable spaghetti straps, and flowing high-low ruffle hem.',
    brand: 'H&M',
    category: mockCategories[1],
    price: 59.99,
    discountPrice: 45.0,
    images: [{ public_id: 'floral_dress_1', url: '/images/dress.jpg' }],
    stock: 40,
    SKU: 'HM-FLORAL-DRESS-S',
    ratings: 4.5,
    numReviews: 32,
    specifications: { material: '100% Polyester chiffon', color: 'Floral / Pink' },
    tags: ['dress', 'summer', 'fashion', 'floral', 'clothing'],
    isFeatured: true,
    isActive: true
  },
  {
    _id: '6a1fdb4e52daecb390f3d114',
    title: 'Classic Leather Motorcycle Jacket',
    description: 'Timeless asymmetrical black leather motorcycle jacket crafted from genuine lambskin leather. Features heavy-duty silver hardware, zipper cuffs, and quilted lining.',
    brand: 'Zara',
    category: mockCategories[1],
    price: 189.0,
    discountPrice: 159.0,
    images: [{ public_id: 'leather_jacket_1', url: '/images/jacket.jpg' }],
    stock: 12,
    SKU: 'ZARA-LEATHER-JKT-M',
    ratings: 4.7,
    numReviews: 18,
    specifications: { material: 'Genuine Lambskin Leather', color: 'Black' },
    tags: ['jacket', 'leather', 'fashion', 'clothing', 'outerwear'],
    isFeatured: false,
    isActive: true
  },
  {
    _id: '6a1fdb4e52daecb390f3d115',
    title: 'Nike Air Max Running Shoes',
    description: 'Revolutionary cushioning and engineered mesh construct makes these Nike sneakers incredibly comfortable for long-distance runs and everyday walking.',
    brand: 'Nike',
    category: mockCategories[1],
    price: 129.99,
    discountPrice: 109.99,
    images: [{ public_id: 'nike_air_max_1', url: '/images/shoes.jpg' }],
    stock: 30,
    SKU: 'NIKE-AM-RUN-10',
    ratings: 4.6,
    numReviews: 89,
    specifications: { size: '10 US', color: 'Red/Black', sole_material: 'Rubber' },
    tags: ['shoes', 'sneakers', 'nike', 'running', 'fashion', 'footwear'],
    isFeatured: true,
    isActive: true
  },
  {
    _id: '6a1fdb4e52daecb390f3d116',
    title: 'Minimalist Ceramic Vase Set',
    description: 'Set of 3 hand-crafted matte finished ceramic vases. These modern decorative bud vases are perfect for pampas grass or standalone decor.',
    brand: 'IKEA',
    category: mockCategories[2],
    price: 34.99,
    discountPrice: 29.99,
    images: [{ public_id: 'ceramic_vase_1', url: '/images/vase.jpg' }],
    stock: 50,
    SKU: 'IKEA-CERAMIC-VASE-3',
    ratings: 4.6,
    numReviews: 45,
    specifications: { material: 'Stoneware', pieces: '3 vases' },
    tags: ['vase', 'home decor', 'ceramic', 'living room', 'minimalist'],
    isFeatured: true,
    isActive: true
  },
  {
    _id: '6a1fdb4e52daecb390f3d117',
    title: 'Velvet Matte Lipstick - Ruby Woo',
    description: 'An iconic retro matte lipstick formula that delivers intense color payoff and a complete matte finish. Long-wearing and smudge-proof.',
    brand: 'MAC',
    category: mockCategories[3],
    price: 22.0,
    discountPrice: 18.5,
    images: [{ public_id: 'mac_lipstick_1', url: '/images/lipstick.jpg' }],
    stock: 100,
    SKU: 'MAC-MATTE-LIPSTICK-RW',
    ratings: 4.9,
    numReviews: 215,
    specifications: { shade: 'Ruby Woo (Matte)' },
    tags: ['lipstick', 'beauty', 'makeup', 'lip care', 'cosmetics'],
    isFeatured: true,
    isActive: true
  },
  {
    _id: '6a1fdb4e52daecb390f3d118',
    title: 'LEGO Star Wars Millennium Falcon',
    description: 'Build and display the legendary Corellian freighter! Detailed cockpit, detailed interior, and rotating gun turrets.',
    brand: 'LEGO',
    category: mockCategories[6],
    price: 159.99,
    discountPrice: 139.99,
    images: [{ public_id: 'lego_falcon', url: '/images/lego_falcon.jpg' }],
    stock: 10,
    SKU: 'LEGO-SW-FALCON',
    ratings: 4.9,
    numReviews: 120,
    specifications: { pieces: '1351', age_recommendation: '9+' },
    tags: ['lego', 'toys', 'star wars', 'falcon', 'building blocks'],
    isFeatured: true,
    isActive: true
  }
];

module.exports = { mockCategories, mockProducts };
